language:  cpp

matrix:
  include:
    - os:        osx
      osx_image: xcode11.5
      install:
        - pip3 install --user pytest pygments
      env:
        - TARGET=mac TEST=test

#   - os:        osx
#     osx_image: xcode7.3
#     env:
#       - TARGET=mac TEST=test-cpp

    - os:        linux
      dist:      xenial
      install:
        - sudo apt-get install -y python3-pip
        - pip3 install --user pytest pygments
      env:
        - TARGET=linux TEST=test

    - os:        linux
      services:
        - docker
      before_install:
        - docker run -d --name focal -v $(pwd):/procyon -w /procyon ubuntu:focal sleep infinity
        - docker ps
      install:
        - $SH apt-get update
        - $SH apt-get install -y --no-install-recommends python build-essential clang make
        - $SH apt-get install -y --no-install-recommends python3 python3-pip
        - $SH pip3 install --user pytest pygments
      env:
        - TARGET=linux TEST=test SH="docker exec focal"

    - os:        linux
      services:
        - docker
      before_install:
        - docker run -d --name focal -v $(pwd):/procyon -w /procyon ubuntu:focal sleep infinity
        - docker ps
      install:
        - $SH DEBIAN_FRONTEND=noninteractive apt-get update
        - $SH DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends python build-essential clang make
        - $SH DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends mingw-w64 xvfb wine
      env:
        - TARGET=win TEST=test-wine SH="docker exec focal"

script:
  - $SH ./configure -o $TARGET
  - $SH make
  - $SH make $TEST
