language:  cpp

env:
- "TEST=make test"

matrix:
  include:
    - os:        osx
      osx_image: xcode9.3
      install:   brew upgrade python && pip3 install --user pytest pygments

    - os:        osx
      osx_image: xcode7.3
      env:
        - "TEST=python3 -m pytest src"

    - os:        linux
      dist:      trusty
      install:   sudo apt-get install python3-pip && pip3 install --user pytest pygments

script: ./configure && make && $TEST
