language:  cpp

matrix:
  include:
    - os:        osx
      osx_image: xcode13.2
      install:
        - pip3 install --user pytest pygments
      env:
        - TARGET=mac TEST=test

#   - os:        osx
#     osx_image: xcode7.3
#     env:
#       - TARGET=mac TEST=test-cpp

script:
  - $SH ./configure -o $TARGET
  - $SH make
  - $SH make $TEST
